### ISSUE TITLE
Initial Todo

### ISSUE THREAD

**Issue by abkfenris** [abkfenris/ResinDashboard#1]
- [ ] Core Data Models - include a findOrCreate method
  - [ ] Application
  - [ ] Device
- [ ] Save token in Keychain
- [ ] Save view settings in UserDefaults
- [ ] Connect Core Data Models
  - [ ] Application
  - [ ] Device
  - [ ] Make sure to use a Set and remove extra Applications and Devices
- [ ] Map device locations, and allow custom device locations to overrride discovered device locations
- [ ] Non destructive Application and Device actions
- [ ] Find out from Resin.io about using art assets and submitting to App Store
- [ ] Let Resin.io know when it's ready for others to use
